CREATE TABLE competition (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    participant_type VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,

    CONSTRAINT ck_competition_participant_type
        CHECK (participant_type IN ('INDIVIDUAL', 'TEAM')),

    CONSTRAINT ck_competition_status
        CHECK (status IN ('OPEN', 'IN_MATCH', 'COMPLETED'))
);
