CREATE TABLE participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    members JSONB,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_participant_competition
        FOREIGN KEY (competition_id)
        REFERENCES competition(id)
        ON DELETE CASCADE,

    CONSTRAINT uk_participant_competition_name
        UNIQUE (competition_id, name)
);

CREATE INDEX idx_participant_competition_created
    ON participant (competition_id, created_at, id);